### ISSUE TITLE
Lang file configuration

### ISSUE THREAD

**Issue by rapidrapids** [freqdec/datePicker#25]
I'd like to propose the following (happy to develop this if you are happy?):
- `deriveLocale` should be completely optional (an option that you can pass into `createDatePicker`), if set to false - then no attempt is made to load a file from `lang/`
- It should be possible to specify the location of lang files, if not located in the same location as datePicker itself.

**Comment by freqdec** [comment]
Hi,

Actually, the "location of language files" thing is already sitting in my development version (that I will push to github - promise!). Due to the way the language stuff has been coded, deriveLocale is only able to work at a global level, not on individual datepickers - it can already be set within the script tag (using JSON) or by using the setGlobalOptions method.

I really have to get the current development version up on github - I shall make a concerted effort to do this by next week! (it normally takes someone to prompt me like this - sad but true I'm afraid!).

Many thanks for the feedback!

**Comment by freqdec** [comment]
You can now pass the key "languageFileLocation" (but only when passing the JSON block within the script tags I'm afraid, it has no effect when passed to the setGlobalOptions method) to set the URI used when downloading the language files. Hope this helps.

**Comment by tbredin** [comment]
Is there a way to make this optional? I need to turn this off (default to english) - I'm working with a CMS configuration (which we're stuck with) that only allows us to upload a single minified js file, so including a lang directory or even specifying a new url is not an option. 

In an case I'm not so wild about making a new request for a language file when this is not usually a feature I want to offer.
