### ISSUE TITLE
CSS - avoid having to manually fix CSS file

### ISSUE THREAD

**Issue by TimGS** [freqdec/datePicker#35]
Currently the CSS file asks developers to find/replace the URL path to the media directory.

Can this just be ../media/ in the CSS file as supplied?

This also avoids upgrades wiping the fixed URLs.

-- Tim.

**Comment by freqdec** [comment]
Hi Tim,

This is only actually a requirement if you want to support IE 6 & 7 (IE6 especially as the AlphaImageLoader requires an absolute URL). This is info I should really add to the CSS file.

It might also be beneficial to add a "no old IE" CSS file to the repo (that would require no configuration at all due to the images being Base64 encoded within)?

**Comment by freqdec** [comment]
Hi again, I shall also note in the release notes if the CSS file has changed.
